version: '3'

services:
    web-node-js:
        image: piyapandocker/workshop-test:latest
        ports:
            - "3000:3000"
        environment:
            - MONGODB_ADDON_URI=mongodb://mongodb:27017/test
    mongodb:
        image: mongo:latest
        ports: 
            - "27017:27017"
    chrome:
        image: selenium/node-chrome:4.3.0-20220706
        shm_size: 2gb
        depends_on:
            - selenium-hub
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    selenium-hub:
        image: selenium/hub:4.3.0-20220706
        container_name: selenium-hub
        ports:
            - "4442:4442"
            - "4443:4443"
            - "4444:4444"